ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
    -   id: ruff
        name: "Ruff linter"
        args: [--fix, {{ cookiecutter.underscored }}/]
    -   id: ruff-format
        name: "Ruff formatter"
        args: [{{ cookiecutter.underscored }}/]

-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.51"
    hooks:
      - id: check-manifest
        stages: [manual]

-   repo: local
    hooks:
    -   id: mkdocs-build
        name: "Build documentation"
        description: "Build the documentation with mkdocs"
        files: 'docs/'
        entry: .hooks/mkdocs-build.sh
        language: system
        pass_filenames: false
