---
name: Continuous Integration ğŸ”„

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  pre-commit:
    name: Run pre-commit hooks ğŸª
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository ğŸ§©
        uses: actions/checkout@v4
      - name: Set up Python ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
      - name: Run pre-commit hooks ğŸª
        uses: pre-commit/action@v3.0.1
...
